version: "3"

services:
  messagebus:
    image: rabbitmq:latest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"

  devopsapp:
    build: ./DevopsApp
    command: npm run dev
    ports:
      - "5000:5000"
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      messagebus:
        condition: service_healthy
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://wordleAppDB:27017
      - MESSAGE_QUEUE=amqp://messagebus

  loggingapi:
    build: ./LoggingAPI
    command: npm start
    ports:
      - "5030:5030"
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      devopsapp:
        condition: service_started
      messagebus:
        condition: service_healthy
    environment:
      - PORT=5030
      - MONGO_URL=mongodb://loggingdb:27017
      - MESSAGE_QUEUE=amqp://messagebus

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml

volumes:
  prometheus-data: